### ISSUE TITLE
Outdated Documentation?

### ISSUE THREAD

**Issue by free-x** [quantenschaum/mapping#1]
Hi @quantenschaum ,

first of all thanks for very interesting project. I just want to try your  procedure and found some inconsistencies in your documentation
It is about section https://github.com/quantenschaum/mapping#map-tiles
1. Download ENC
Missing path where ZIP with ENCs should be placed. (./data)
2. make unzip
The rule were in missing 
``` make: *** No rule to make target 'unzip'.  Stop.```
3. make shape
The rule were in missing
```make: *** No rule to make target 'shape'.  Stop.```
For 2. and 3. is now ```make waddenzee``` a right command?

In section https://github.com/quantenschaum/mapping#qgis-server
- make docker
Rule doesn't exist. I executed this manualy
```
docker build -t qgis-server .
docker compose up -d
```

Regards
free-x

**Comment by quantenschaum** [comment]
Thanks for the hints. Yes, it's all a bit quick and dirty. I updated the docs (a bit).

**Comment by quantenschaum** [comment]
The qgis server does currently not work as it seem.

**Comment by free-x** [comment]
Hi,

I missed some infos about requirements. Here is small Howto for Debian/Bookworm

1. jq, python-is-python3 gdal-bin
2. Packages from bookworm-backports
```
sudo apt install -t bookworm-backports qgis qgis-server-bin qgis-server-wms
```

Small correction
With "make serve"  HTTP server is started on port 8002 and not on 8003 as stated in documenation

**Comment by quantenschaum** [comment]
Thanks.

- `jq` is optional, I removed it, was just for easier human reading of the json files
- yes, all python is python 3
- the port was a typo

fixed that
