### ISSUE TITLE
Colors and Icons

### ISSUE THREAD

**Issue by free-x** [quantenschaum/mapping#2]
Hi @quantenschaum 

I opened a map.qgs in QGIS and my charts doesn't look as great as yours :-)
I added Icons to SVG path. 
Here is screenshot 
![image](https://github.com/quantenschaum/mapping/assets/1073657/fbc476fc-0409-45fe-ad7f-4b8e28a5f8a9)
Any Ideas what I'm missing?

Regards
free-x

**Comment by quantenschaum** [comment]
Good questions. What version QGSI do you use? I have 3.28. The icon path is not a must, the qgis xml file contains relative paths to the icons. Seems like the styling for the layers is not working.

**Comment by free-x** [comment]
>  What version QGIS do you use? I have 3.28.

Yes. that was the crucial question. 
On the Ubuntu Focal 20.04 only QGIS 3.10 is/was available
Now I have installed project on Debian Bookworm + QGIS from backports (3.28). And that looks very good in the installation
![image](https://github.com/quantenschaum/mapping/assets/1073657/3f3349ec-f58f-4677-a0ba-3641ede62d93)

**Comment by quantenschaum** [comment]
Nice. I know, it's all a bit messy. Still work in progress and the repo is more like a publicly readable backup of my work. Anyways, it might be useful to someone.

**Comment by quantenschaum** [comment]
FYI I updated the project with focus on german charts (`bsh.qgs`). They look much better now and render much faster.

**Comment by free-x** [comment]
Hi @quantenschaum 

I pulled your new master branch and icons for buoys/beacons/shapes are not  recognized
Thanks for the progress anyway

![image](https://github.com/quantenschaum/mapping/assets/1073657/6dad4b80-9a99-46ca-88f4-bf1f8f090c9f)

**Comment by quantenschaum** [comment]
please run `make icons`

**Comment by free-x** [comment]
ok.....it's very strange

Executed
```
$ make icons
make: Nothing to be done for 'icons'.
```
I have executed manualy all commands from rule
```
~/mapexperiments/mapping$ cd icons/
~/mapexperiments/mapping/icons$ ./genicons.py
....
```
After that it looks much better
![image](https://github.com/quantenschaum/mapping/assets/1073657/1d76d66c-d588-4e47-b204-634e68cc31fc)

Ok. One step further

**Comment by quantenschaum** [comment]
probably there was already a `icons/gen` dir :shrug: the [icons can be used in JOSM](https://github.com/OpenNauticalChart/josm/issues/25#issuecomment-1772280416) if you like
