### ISSUE TITLE
Ship Simulator as a Plugin

### ISSUE THREAD

**Issue by oxbown** [quantenschaum/mapping#5]
I´m digging in the code of ship_sim.py and I think that it is fascinating. Useful to test software, especially AvNav.
It could be a good idea to separate the concept into a separate project.
https://github.com/quantenschaum/mapping/blob/a5b6777950c2879dcc4b03a2fcbab57a37d285fe/ship_sim.py

Similar to https://opencpn.org/OpenCPN/plugins/shipdriver.html
Ais targets could follow a route defined in a json file for example.

**Comment by quantenschaum** [comment]
>I think that it is fascinating. 

little exaggerated

>Useful to test software, especially AvNav.

That was the intention, a simple script to feed meaningful and reproducible data into AvNav or other software to test them at home.

>It could be a good idea to separate the concept into a separate project.

Yes, starting as single file project...

>Similar to https://opencpn.org/OpenCPN/plugins/shipdriver.html

Thanks for the link, didn't know that before.

>Ais targets could follow a route defined in a json file for example.

Sure, there is much room for improvement.

**Comment by quantenschaum** [comment]
>Ship Simulator as a Plugin

You mean, it should be turned into a plugin for AvNav?

**Comment by quantenschaum** [comment]
That is possible. The simulated ship(s) could controlled via a config file that the user can edit in the web UI and the "autopilot" (ship goes to next waypoint).

**Comment by oxbown** [comment]
> That is possible. The simulated ship(s) could controlled via a config file that the user can edit in the web UI and the "autopilot" (ship goes to next waypoint).

This is the idea, the waypoints could be in a closed loop so the ship will make an endless route.

> You mean, it should be turned into a plugin for AvNav?

Could be or not...

**Comment by quantenschaum** [comment]
moved https://github.com/quantenschaum/nmea_ship_sim

**Comment by quantenschaum** [comment]
There is first version of a plugin for AvNav now in the new repo.
